services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
    command: sh -c "npm run start:dev"

  frontend:
    build:
      context: ./frontend
      args:
        - PUBLIC_BACKEND_BASE_URL=${PUBLIC_BACKEND_BASE_URL}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  db_data:
